site_title = "New Papers Pipelines"
limit_days = 7
cache_url = "https://merrillli.github.io/newpapers/cache.json"

[[sources]]
limit = 150
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 150
category = "cs.LG"
title = "Machine Learning"

[[sources]]
limit = 150
category = "cs.IR"
title = "Information Retrieval"



[[sources]]
limit = 150
category = "cs.NI"
title = "Computer Network"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
